# Matrizen in Python
## Sandbox

In [3]:
def scalarVectorMult(x, A):
    return [x * a for a in A]

In [4]:
def scalarMatrixMult(x, A):
    return [scalarVectorMult(x, row) for row in A]

### Matrixmultiplikation

In [13]:
import numpy as np

A = np.array( ((2,3),(3,5)) )
B = np.matrix( ((1,2),(5,-1)) )

np.dot(A, B)

matrix([[17,  1],
        [28,  1]])

In [17]:
A = np.matrix( ((1,2,-3,1),(5,0,6,1)) ) # 2x4
B = np.matrix( ((1,8,-1),(0,0,1),(0.5,-1,-2),(-1,0,4)) ) # 4x3
np.dot(A, B) # OK -> 2x4 = 4x3

"""
np.dot(B, A) # Nicht OK - > 4x2 = 3x4
"""

matrix([[ -1.5,  11. ,  11. ],
        [  7. ,  34. , -13. ]])

### Spiegelt die Matrix an der Hauptdiagonale

In [19]:
A = np.matrix( ((1,2,-3,1),(5,0,6,1)) ) # 2x4
A.transpose()

matrix([[ 1,  5],
        [ 2,  0],
        [-3,  6],
        [ 1,  1]])

### Matrix invertieren

In [41]:
from numpy.linalg import inv
A = np.matrix( ((1,2,1),(4,2,4),(1,2,3)) )
inv(A)

matrix([[ 0.16666667,  0.33333333, -0.5       ],
        [ 0.66666667, -0.16666667,  0.        ],
        [-0.5       ,  0.        ,  0.5       ]])

In [42]:
A * inv(A) # Ergibt die Einheitsmatrix

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Matrizen mit Sympy rechnen

In [24]:
from sympy import *

In [25]:
init_printing()

In [46]:
A = Matrix([[1,2,3],[4,5,6],[7,8,9]])
A

⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

In [47]:
# Transportieren
A.T

⎡1  4  7⎤
⎢       ⎥
⎢2  5  8⎥
⎢       ⎥
⎣3  6  9⎦

In [48]:
B = Matrix([[2,2,2],[3,3,3],[4,4,4]])
A * B, B * A

⎛⎡20  20  20⎤  ⎡24  30  36⎤⎞
⎜⎢          ⎥  ⎢          ⎥⎟
⎜⎢47  47  47⎥, ⎢36  45  54⎥⎟
⎜⎢          ⎥  ⎢          ⎥⎟
⎝⎣74  74  74⎦  ⎣48  60  72⎦⎠

In [51]:
# Wichtige Rechenregel!!!
(A * B).T, B.T * A.T

⎛⎡20  47  74⎤  ⎡20  47  74⎤⎞
⎜⎢          ⎥  ⎢          ⎥⎟
⎜⎢20  47  74⎥, ⎢20  47  74⎥⎟
⎜⎢          ⎥  ⎢          ⎥⎟
⎝⎣20  47  74⎦  ⎣20  47  74⎦⎠

In [52]:
A = Matrix([[1,2,1],[4,2,4],[1,2,3]])
A.inv()

⎡1/6   1/3   -1/2⎤
⎢                ⎥
⎢2/3   -1/6   0  ⎥
⎢                ⎥
⎣-1/2   0    1/2 ⎦

In [53]:
A * A.inv() # Ergibt die Einheitsmatrix

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦