# Matrizen in Python
## Sandbox

In [1]:
def scalarVectorMult(x, A):
    return [x * a for a in A]

In [2]:
def scalarMatrixMult(x, A):
    return [scalarVectorMult(x, row) for row in A]

### Matrixmultiplikation

In [3]:
import numpy as np

A = np.array( ((2,3),(3,5)) )
B = np.matrix( ((1,2),(5,-1)) )

np.dot(A, B)

matrix([[17,  1],
        [28,  1]])

In [4]:
A = np.matrix( ((1,2,-3,1),(5,0,6,1)) ) # 2x4
B = np.matrix( ((1,8,-1),(0,0,1),(0.5,-1,-2),(-1,0,4)) ) # 4x3
np.dot(A, B) # OK -> 2x4 = 4x3

"""
np.dot(B, A) # Nicht OK - > 4x2 = 3x4
"""

'\nnp.dot(B, A) # Nicht OK - > 4x2 = 3x4\n'

### Spiegelt die Matrix an der Hauptdiagonale

In [5]:
A = np.matrix( ((1,2,-3,1),(5,0,6,1)) ) # 2x4
A.transpose()

matrix([[ 1,  5],
        [ 2,  0],
        [-3,  6],
        [ 1,  1]])

### Matrix invertieren

In [6]:
from numpy.linalg import inv
A = np.matrix( ((1,2,1),(4,2,4),(1,2,3)) )
inv(A)

matrix([[ 0.16666667,  0.33333333, -0.5       ],
        [ 0.66666667, -0.16666667,  0.        ],
        [-0.5       ,  0.        ,  0.5       ]])

In [7]:
A * inv(A) # Ergibt die Einheitsmatrix

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Matrizen mit Sympy rechnen

In [8]:
from sympy import *

In [9]:
init_printing()

In [10]:
A = Matrix([[1,2,3],[4,5,6],[7,8,9]])
A

⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

In [11]:
# Transportieren
A.T

⎡1  4  7⎤
⎢       ⎥
⎢2  5  8⎥
⎢       ⎥
⎣3  6  9⎦

In [12]:
B = Matrix([[2,2,2],[3,3,3],[4,4,4]])
A * B, B * A

⎛⎡20  20  20⎤  ⎡24  30  36⎤⎞
⎜⎢          ⎥  ⎢          ⎥⎟
⎜⎢47  47  47⎥, ⎢36  45  54⎥⎟
⎜⎢          ⎥  ⎢          ⎥⎟
⎝⎣74  74  74⎦  ⎣48  60  72⎦⎠

In [13]:
# Wichtige Rechenregel!!!
(A * B).T, B.T * A.T

⎛⎡20  47  74⎤  ⎡20  47  74⎤⎞
⎜⎢          ⎥  ⎢          ⎥⎟
⎜⎢20  47  74⎥, ⎢20  47  74⎥⎟
⎜⎢          ⎥  ⎢          ⎥⎟
⎝⎣20  47  74⎦  ⎣20  47  74⎦⎠

In [14]:
A = Matrix([[1,2,1],[4,2,4],[1,2,3]])
A.inv()

⎡1/6   1/3   -1/2⎤
⎢                ⎥
⎢2/3   -1/6   0  ⎥
⎢                ⎥
⎣-1/2   0    1/2 ⎦

In [15]:
A * A.inv() # Ergibt die Einheitsmatrix

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

## Lineare Gleichungssysteme
### Gauss-Verfahren

In [16]:
M = [[1,2,3],[4,5,6],[1,1,1]]
M

In [17]:
def rowMod(M, i, j, factor):
    """
    Elementare Zeilenumformung Type 3
    Addiere zur i-ten Zweile das x-fache der j-ten Zeile
    M wird modifiziert!
    """
    M[i] = [a + factor * b for a, b in zip(M[i], M[j])]

In [18]:
rowMod(M, 0, 1, 3)
M

In [19]:
"""
Umwandeln in ZSF
"""
def rowEchelon(M):
    row, col = 0, 0
    rows, cols = len(M), len(M[0])
    while row < rows and col < cols:
        # versuche, Pivotelement zu finden
        if M[row][col] == 0:
            # die Zeilen unter row durchgehen:
            for r in range(row + 1, rows):
                if M[r][col] != 0:
                    rowMod(M, row, r, 1)
                    break
        if M[row][col] == 0:
            col += 1
            continue
        pivot = M[row][col]
        for r in range(row + 1, rows):
            if M[r][col] != 0:
                rowMod(M, r, row, -M[r][col] / pivot)
        row += 1
        col += 1

In [20]:
M = [[1,2,3],[4,5,6],[-3,0,12]]
rowEchelon(M)
M

In [21]:
# Achtung Fliesskomaarithmetik
M = [[6,-1,-1,4],[1,1,10,-6],[2,-1,1,-2]]
rowEchelon(M)
M

In [22]:
# Nur zum Aufzeigen
"""
def identityMatrix(n):
    E = [[0] * n for i in range(n)]
    for i in range(n):
        E[i][i] = 1
    return E

def type3Matrix(n, i, j, factor):
    A = identityMatrix(n)
    A[i][j] = x
    return A

def rowMod(M, i, j, factor):
    return matrixProd(type3Matrix(len(M), i, j, factor), M)
"""

'\ndef identityMatrix(n):\n    E = [[0] * n for i in range(n)]\n    for i in range(n):\n        E[i][i] = 1\n    return E\n\ndef type3Matrix(n, i, j, factor):\n    A = identityMatrix(n)\n    A[i][j] = x\n    return A\n\ndef rowMod(M, i, j, factor):\n    return matrixProd(type3Matrix(len(M), i, j, factor), M)\n'

## Determinante berechnen

In [23]:
def determinant(M):
    rowEchelon(M)
    det = 1
    for i in range(len(M)):
        det *= M[i][i]
    return det

M = [[6,-1,-1],[1,1,10],[2,-1,1]]
determinant(M)

### Mit Sympy

In [24]:
from sympy import *
A = Matrix([[6,-1,-1,4],[1,1,10,-6],[2,-1,1,-2]])
A.rref()

⎛⎡1  0  0  1 ⎤           ⎞
⎜⎢           ⎥           ⎟
⎜⎢0  1  0  3 ⎥, (0, 1, 2)⎟
⎜⎢           ⎥           ⎟
⎝⎣0  0  1  -1⎦           ⎠

In [25]:
from sympy.abc import x, y, z
linsolve(A, [x,y,z])

In [26]:
C = Matrix([[6,-1,-1],[1,1,10],[2,-1,1]])
b = Matrix([4,-6,-2])
linsolve((C,b), [x,y,z])

In [27]:
A = Matrix([[6,-1,-1],[1,1,10],[2,-1,1]])
A.det()

In [28]:
A = Matrix([[6,-1,-1],[1,1,10],[2,-1,1]])
A.inv()

⎡ 11               ⎤
⎢ ──    1/25  -9/50⎥
⎢ 50               ⎥
⎢                  ⎥
⎢ 19          -61  ⎥
⎢ ──    4/25  ──── ⎥
⎢ 50           50  ⎥
⎢                  ⎥
⎣-3/50  2/25  7/50 ⎦

In [29]:
from sympy import *
A = Matrix([[1,10,11],[2,20,22],[3,30,33]])
A.det()

In [30]:
from sympy import *
A = Matrix([[11,12,13],[21,22,23],[31,32,33]])
A.det()

In [31]:
from sympy import *
A = Matrix([[-1,1],[1,2]])
B = Matrix([[3,2],[1,-2],[0,1]])
a = Matrix([[-1],[2]])
I2 = Matrix([[1,0],[0,1]]) 

In [32]:
A * A * A

⎡-1  4 ⎤
⎢      ⎥
⎣4   11⎦

In [33]:
A * B

ShapeError: Matrix size mismatch: (2, 2) * (3, 2).

In [34]:
B*A

⎡-1  7 ⎤
⎢      ⎥
⎢-3  -3⎥
⎢      ⎥
⎣1   2 ⎦

In [35]:
A*B.T

⎡-1  -3  1⎤
⎢         ⎥
⎣7   -3  2⎦

In [36]:
B*(A-I2)

⎡-4  5 ⎤
⎢      ⎥
⎢-4  -1⎥
⎢      ⎥
⎣1   1 ⎦

In [37]:
a.T*A*a

[3]